import { PredefinedConfig } from 'adaptableblotter/types';

export default {
  Layout: {
    CurrentLayout: 'MyGlobal',
    Layouts: [
      {
        Columns: [
          'Order ID',
          'Account Code',
          'Account Name',
          'Side',
          'Amount',
          'Ticker',
          'Security Name',
          'USD Principal',
          'Executed Shares',
          'Average Price',
          'Leaves',
          'Exchange Code',
          'Exchange Name',
          'Region',
          'Order Type',
          'Limit Price',
          'Time In Force',
          'Expiry Date',
          'Stop Price',
          'Locate Status',
          'GTC Total Target Shares',
          'GTC Total Executed Shares',
          'Trader ID',
          'Trader Name',
          'Last Price Local',
          'Last Price USD',
          'Directed Order',
          'Benchmark',
          'Clearing Method',
          'Trade Status',
          'Cancel Status',
          'Cross Trade',
          'Client Trader',
          'Client Notes',
          'TCA Notes',
          'TCA Exclude from LiquidMetrix',
          'TCA Include Premarket',
          'Date Created',
          'USD Commission',
          'Local Commission',
          'Currency',
          'Spot FX Rate',
          'Client Comm Rate',
          'Client Comm Type',
          'Research Credit Rate',
          'Broker Code',
          'Broker Comm Rate',
          'Broker Comm Type',
          'Verified By',
          'Order Source',
          'High',
          'Low',
          'VWAP',
          'Arrival',
          'Closing Price',
          'Portfolio',
          'Execution Reason Code',
          'Reason for Accepting Max USD Principal',
          'Trade Date',
          'Settle Date',
          'Archive Flag',
          'Order Status',
          'Original Order ID',
          'FIX Acceptor ClOrdId',
          'Broadcort File Sent',
          'Broadcort File',
          'FCA2 Sent File',
          'FCA2 File',
          'Client LEI',
          'ETC Status',
          'Settle Avg Price',
          'Settle Currency',
          'Settle FX Rate',
          'Settle FX Type',
          'Prince Decimal Places',
          'Money Decimal Places',
          'Done for Day Flag',
          'Settle Method Code',
          'EMAIL SENT',
          'Clearing Fee',
          'Clearing Fee Currency',
          'Tax Stamp Meth',
        ],
        ColumnSorts: [],
        Name: 'Ab_Default_Layout',
        VendorGridInfo: {
          GroupState: null,
          ColumnState:
            '[{"colId":"Order ID","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Account Code","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Account Name","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Side","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Amount","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Ticker","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Security Name","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"USD Principal","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Executed Shares","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Average Price","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Leaves","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Exchange Code","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Exchange Name","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Region","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Order Type","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Limit Price","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Time In Force","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Expiry Date","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Stop Price","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Locate Status","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"GTC Total Target Shares","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"GTC Total Executed Shares","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Trader ID","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Trader Name","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Last Price Local","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Last Price USD","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Directed Order","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Benchmark","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Clearing Method","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Trade Status","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Cancel Status","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Cross Trade","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Client Trader","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Client Notes","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"TCA Notes","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"TCA Exclude from LiquidMetrix","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"TCA Include Premarket","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Date Created","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"USD Commission","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Local Commission","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Currency","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Spot FX Rate","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Client Comm Rate","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Client Comm Type","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Research Credit Rate","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Broker Code","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Broker Comm Rate","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Broker Comm Type","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Verified By","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Order Source","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"High","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Low","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"VWAP","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Arrival","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Closing Price","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Portfolio","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Execution Reason Code","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Reason for Accepting Max USD Principal","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Trade Date","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Settle Date","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Archive Flag","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Order Status","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Original Order ID","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"FIX Acceptor ClOrdId","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Broadcort File Sent","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Broadcort File","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"FCA2 Sent File","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"FCA2 File","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Client LEI","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"ETC Status","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Settle Avg Price","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Settle Currency","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Settle FX Rate","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Settle FX Type","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Prince Decimal Places","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Money Decimal Places","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Done for Day Flag","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Settle Method Code","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"EMAIL SENT","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Clearing Fee","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Clearing Fee Currency","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null},{"colId":"Tax Stamp Meth","hide":false,"aggFunc":null,"width":200,"pivotIndex":null,"pinned":null,"rowGroupIndex":null}]',
        },
      },
      {
        Name: 'MyOrders',
        Columns: [
          'Order ID',
          'Account Code',
          'Side',
          'Amount',
          'Ticker',
          'Security Name',
          'Executed Shares',
          'Leaves',
          'Order Type',
          'Benchmark',
          'Region',
          'Account Name',
          'USD Principal',
          'Average Price',
          'Exchange Code',
          'Exchange Name',
          'Limit Price',
          'Time In Force',
          'Expiry Date',
          'Stop Price',
          'Locate Status',
          'Trader ID',
          'Trader Name',
          'Directed Order',
          'Cross Trade',
          'Trade Status',
          'Clearing Method',
          'Cancel Status',
          'Client Trader',
          'Client Notes',
          'TCA Notes',
          'TCA Exclude from LiquidMetrix',
          'TCA Include Premarket',
          'Date Created',
          'Client Comm Rate',
          'Client Comm Type',
          'Research Credit Rate',
          'Broker Code',
          'Broker Comm Rate',
          'Broker Comm Type',
          'Verified By',
          'Order Source',
          'High',
          'Low',
          'VWAP',
          'Arrival',
          'Closing Price',
          'Portfolio',
          'Execution Reason Code',
          'Archive Flag',
          'Order Status',
        ],
        ColumnSorts: [],
        VendorGridInfo: null,
      },
      {
        Name: 'MyDesk',
        Columns: [
          'Order ID',
          'Account Code',
          'Side',
          'Amount',
          'Ticker',
          'Security Name',
          'Executed Shares',
          'Leaves',
          'Order Type',
          'Benchmark',
          'Region',
          'Account Name',
          'USD Principal',
          'Average Price',
          'Exchange Code',
          'Exchange Name',
          'Limit Price',
          'Time In Force',
          'Expiry Date',
          'Stop Price',
          'Locate Status',
          'Trader ID',
          'Trader Name',
          'Directed Order',
          'Cross Trade',
          'Trade Status',
          'Clearing Method',
          'Cancel Status',
          'Client Trader',
          'Client Notes',
          'TCA Notes',
          'TCA Exclude from LiquidMetrix',
          'TCA Include Premarket',
          'Date Created',
          'Client Comm Rate',
          'Client Comm Type',
          'Research Credit Rate',
          'Broker Code',
          'Broker Comm Rate',
          'Broker Comm Type',
          'Verified By',
          'Order Source',
          'High',
          'Low',
          'VWAP',
          'Arrival',
          'Closing Price',
          'Portfolio',
          'Execution Reason Code',
          'Archive Flag',
          'Order Status',
        ],
        ColumnSorts: [],
        VendorGridInfo: null,
      },
      {
        Name: 'MyGlobal',
        Columns: [
          'Order ID',
          'Account Code',
          'Side',
          'Amount',
          'Ticker',
          'Security Name',
          'Executed Shares',
          'Leaves',
          'Order Type',
          'Benchmark',
          'Region',
          'Account Name',
          'USD Principal',
          'Average Price',
          'Exchange Code',
          'Exchange Name',
          'Limit Price',
          'Time In Force',
          'Expiry Date',
          'Stop Price',
          'Locate Status',
          'Trader ID',
          'Trader Name',
          'Directed Order',
          'Cross Trade',
          'Trade Status',
          'Clearing Method',
          'Cancel Status',
          'Client Trader',
          'Client Notes',
          'TCA Notes',
          'TCA Exclude from LiquidMetrix',
          'TCA Include Premarket',
          'Date Created',
          'Client Comm Rate',
          'Client Comm Type',
          'Research Credit Rate',
          'Broker Code',
          'Broker Comm Rate',
          'Broker Comm Type',
          'Verified By',
          'Order Source',
          'High',
          'Low',
          'VWAP',
          'Arrival',
          'Closing Price',
          'Portfolio',
          'Execution Reason Code',
          'Archive Flag',
          'Order Status',
        ],
        ColumnSorts: [],
        VendorGridInfo: null,
      },
      {
        Name: 'TCA Recap',
        Columns: [
          'Side',
          'Executed Shares',
          'Ticker',
          'Security Name',
          'Average Price',
          'Broker Code',
          'Broker Comm Rate',
          'Broker Comm Type',
        ],
        ColumnSorts: [],
        VendorGridInfo: null,
      },
    ],
  },
  ConditionalStyle: {
    ConditionalStyles: [
      {
        ColumnId: '',
        ColumnCategoryId: '',
        Style: {
          BackColor: '#80ffff',
          ForeColor: '#000000',
          FontWeight: 'Normal',
          FontStyle: 'Normal',
          ClassName: '',
        },
        ConditionalStyleScope: 'Row',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Side',
              ColumnDisplayValues: ['BUY'],
              ColumnRawValues: ['BUY'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        ColumnId: '',
        ColumnCategoryId: '',
        Style: {
          BackColor: '#ff8080',
          FontWeight: 'Normal',
          FontStyle: 'Normal',
          ClassName: '',
        },
        ConditionalStyleScope: 'Row',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Side',
              ColumnDisplayValues: ['SELL'],
              ColumnRawValues: ['SELL'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        ColumnId: '',
        ColumnCategoryId: '',
        Style: {
          BackColor: '#d7ffff',
          FontWeight: 'Normal',
          FontStyle: 'Normal',
          ClassName: '',
        },
        ConditionalStyleScope: 'Row',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Side',
              ColumnDisplayValues: ['BUY COVER'],
              ColumnRawValues: ['BUY COVER'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        ColumnId: '',
        ColumnCategoryId: '',
        Style: {
          BackColor: '#ffd2d2',
          FontWeight: 'Normal',
          FontStyle: 'Normal',
          ClassName: '',
        },
        ConditionalStyleScope: 'Row',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Side',
              ColumnDisplayValues: ['SELL SHORT'],
              ColumnRawValues: ['SELL SHORT'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        ColumnId: 'Order ID',
        ColumnCategoryId: '',
        Style: {
          BackColor: '#ffff80',
          FontWeight: 'Normal',
          FontStyle: 'Normal',
          ClassName: '',
        },
        ConditionalStyleScope: 'Column',
        Expression: {
          ColumnValueExpressions: [],
          FilterExpressions: [
            {
              ColumnId: 'Benchmark',
              Filters: ['Blanks'],
            },
          ],
          RangeExpressions: [],
        },
      },
    ],
  },
  QuickSearch: {
    QuickSearchText: '',
    DisplayAction: 'ShowRowAndHighlightCell',
    Style: {
      BackColor: '#FFFFCC',
      ForeColor: '#000000',
    },
  },
  PercentBar: {
    PercentBars: [
      {
        ColumnId: 'Executed Shares',
        MaxValue: 100,
        MinValue: 0,
        PositiveColor: '#008000',
        NegativeColor: '#FF0000',
        ShowValue: true,
        MaxValueColumnId: 'Amount',
        MinValueColumnId: undefined,
      },
      {
        ColumnId: 'Leaves',
        MaxValue: 100,
        MinValue: 0,
        PositiveColor: '#008000',
        NegativeColor: '#FF0000',
        ShowValue: true,
        MaxValueColumnId: 'Amount',
        MinValueColumnId: undefined,
      },
    ],
  },
  CellValidation: {
    CellValidations: [
      {
        ActionMode: 'Stop Edit',
        ColumnId: 'Archive Flag',
        Range: {
          Operator: 'NotEquals',
          Operand1: 'Y',
          Operand2: '',
          Operand1Type: 'Value',
          Operand2Type: 'Value',
        },
        Expression: {
          ColumnValueExpressions: [],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        ActionMode: 'Stop Edit',
        ColumnId: 'Benchmark',
        Range: {
          Operator: 'ExistingValuesOnly',
          Operand1: '',
          Operand2: '',
          Operand1Type: 'Value',
          Operand2Type: 'Value',
        },
        Expression: {
          ColumnValueExpressions: [],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
    ],
  },
  UserFilter: {
    UserFilters: [
      {
        Name: 'Deleted',
        ColumnId: 'Order Status',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Order Status',
              ColumnDisplayValues: ['Deleted'],
              ColumnRawValues: ['Deleted'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        Name: 'NotDeleted',
        ColumnId: 'Order Status',
        Expression: {
          ColumnValueExpressions: [],
          FilterExpressions: [],
          RangeExpressions: [
            {
              ColumnId: 'Order Status',
              Ranges: [
                {
                  Operand1Type: 'Value',
                  Operand2Type: 'Value',
                  Operator: 'NotEquals',
                  Operand1: 'Deleted',
                  Operand2: '',
                },
              ],
            },
          ],
        },
      },
      {
        Name: 'NotArchived',
        ColumnId: 'Archive Flag',
        Expression: {
          ColumnValueExpressions: [],
          FilterExpressions: [],
          RangeExpressions: [
            {
              ColumnId: 'Archive Flag',
              Ranges: [
                {
                  Operand1Type: 'Value',
                  Operand2Type: 'Value',
                  Operator: 'NotEquals',
                  Operand1: 'Y',
                  Operand2: '',
                },
              ],
            },
          ],
        },
      },
      {
        Name: 'TraderSB',
        ColumnId: 'Trader ID',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Trader ID',
              ColumnDisplayValues: ['SB'],
              ColumnRawValues: ['SB'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        Name: 'MyOrders',
        ColumnId: 'Trader ID',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Trader ID',
              ColumnDisplayValues: ['SB'],
              ColumnRawValues: ['SB'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
      {
        Name: 'Europe',
        ColumnId: 'Region',
        Expression: {
          ColumnValueExpressions: [
            {
              ColumnId: 'Region',
              ColumnDisplayValues: ['EUROPE', 'BONDS'],
              ColumnRawValues: ['EUROPE', 'BONDS'],
            },
          ],
          FilterExpressions: [],
          RangeExpressions: [],
        },
      },
    ],
  },
  ColumnFilter: {
    ColumnFilters: [
      {
        ColumnId: 'Order Status',
        Filter: {
          ColumnValueExpressions: [],
          FilterExpressions: [
            {
              ColumnId: 'Order Status',
              Filters: ['NotDeleted'],
            },
          ],
          RangeExpressions: [],
        },
      },
      {
        ColumnId: 'Archive Flag',
        Filter: {
          ColumnValueExpressions: [],
          FilterExpressions: [
            {
              ColumnId: 'Archive Flag',
              Filters: ['NotArchived'],
            },
          ],
          RangeExpressions: [],
        },
      },
      {
        ColumnId: 'Trader ID',
        Filter: {
          ColumnValueExpressions: [],
          FilterExpressions: [
            {
              ColumnId: 'Trader ID',
              Filters: ['TraderSB'],
            },
          ],
          RangeExpressions: [],
        },
      },
    ],
  },
} as PredefinedConfig;
